CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 9) PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  category VARCHAR(24) NOT NULL CHECK (category IN ('Makeup', 'Skincare', 'Fragrance', 'Gifting')),
  brand VARCHAR(120),
  sku VARCHAR(64),
  price INTEGER NOT NULL CHECK (price > 0),
  mrp INTEGER NOT NULL CHECK (mrp >= price),
  stock INTEGER NOT NULL CHECK (stock >= 0),
  rating NUMERIC(2, 1) NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
  reviews INTEGER NOT NULL DEFAULT 0 CHECK (reviews >= 0),
  badge VARCHAR(40),
  image VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS products_sku_unique_idx ON products (sku) WHERE sku IS NOT NULL;

CREATE TABLE IF NOT EXISTS product_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id INTEGER NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  position SMALLINT NOT NULL CHECK (position BETWEEN 0 AND 9),
  filename VARCHAR(180) NOT NULL,
  mime_type VARCHAR(32) NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  image_data BYTEA NOT NULL CHECK (octet_length(image_data) BETWEEN 1 AND 307200),
  width SMALLINT NOT NULL CHECK (width BETWEEN 1 AND 1200),
  height SMALLINT NOT NULL CHECK (height BETWEEN 1 AND 1200),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (product_id, position)
);
