-- This migration used to seed six named console accounts that all shared one
-- published password, which meant any deployment could be opened by anyone who
-- had read the README. The demo accounts are gone.
--
-- Nothing is inserted here now. The console is populated by people: an
-- administrator adds a team member, or somebody registers through /signup and an
-- administrator approves them. The one bootstrap administrator is written by
-- src/server/admin.ts with a random secret nobody holds, because
-- password_hash is NOT NULL and the address has to exist before it can be
-- claimed:
--
--   npx tsx scripts/reset-admin-password.ts --email admin@glowngrace.in
--
-- Accounts left over from the old seeds are removed by
-- db/migrations/010_remove_demo_accounts.sql.
SELECT 1;
